name: Lint and Build

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
# add build in future if needed

# build:
#   runs-on: ubuntu-latest
#   container: node:20
#   needs: lint

#   steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4

#     - name: Install dependencies
#       run: npm ci

#     - name: Run build
#       run: npm run build
